image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  - chmod +x /home/appveyor/projects/aqa3-selenium/driver/chromedriver
  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - ./gradlew test --info