image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки


install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов); права на запуск CI для Linux
   - chmod +x gradlew
  - java -jar ./artifacts/app-order.jar &

  -  Build with Gradle


build_script:

  - ./gradlew test --info "-Dselenide.headless=true"