image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off

install:
  - chmod +x gradlew
  - chmod +x chromedriver
  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - ./gradlew test --info