image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов); права на запуск CI для Linux


  - name: install
      run: java -jar ./artifacts/app-mbank.jar &
  - name: Build with Gradle
    run: ./gradlew test --info -Dselenide.headless=true